---
namespace: trippsc2
name: template
version: 1.3.1
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains roles for sealing machines for use as templates.

license_file: 'LICENSE'

tags:
  - infrastructure
  - linux
  - windows

dependencies:
  ansible.windows: ">=2.7.0"
  chocolatey.chocolatey: ">=1.0.0"
  community.windows: ">=2.7.0"

repository: https://github.com/trippsoft/ansible-collection-template.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
