---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/bleachbit/.aar_doc.yml
      - roles/bleachbit/README.md
      - roles/bleachbit/meta/argument_specs.yml
      - roles/bleachbit/meta/main.yml
      - roles/debian/.aar_doc.yml
      - roles/debian/README.md
      - roles/debian/meta/argument_specs.yml
      - roles/debian/meta/main.yml
      - roles/rhel/.aar_doc.yml
      - roles/rhel/README.md
      - roles/rhel/meta/argument_specs.yml
      - roles/rhel/meta/main.yml
      - roles/ubuntu/.aar_doc.yml
      - roles/ubuntu/README.md
      - roles/ubuntu/meta/argument_specs.yml
      - roles/ubuntu/meta/main.yml
      - roles/windows/.aar_doc.yml
      - roles/windows/README.md
      - roles/windows/meta/argument_specs.yml
      - roles/windows/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.template'
jobs:
  docs_bleachbit:
    name: Generate bleachbit role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.template
          ref: main
      - name: Generate bleachbit role documentation
        working-directory: 'trippsc2.template'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/bleachbit
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update bleachbit role documentation." || /bin/true
          git push origin main
          deactivate
  docs_debian:
    name: Generate debian role documentation
    needs: docs_bleachbit
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.template
          ref: main
      - name: Generate debian role documentation
        working-directory: 'trippsc2.template'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/debian
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update debian role documentation." || /bin/true
          git push origin main
          deactivate
  docs_rhel:
    name: Generate rhel role documentation
    needs: docs_debian
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.template
          ref: main
      - name: Generate rhel role documentation
        working-directory: 'trippsc2.template'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/rhel
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update rhel role documentation." || /bin/true
          git push origin main
          deactivate
  docs_ubuntu:
    name: Generate ubuntu role documentation
    needs: docs_rhel
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.template
          ref: main
      - name: Generate ubuntu role documentation
        working-directory: 'trippsc2.template'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/ubuntu
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update ubuntu role documentation." || /bin/true
          git push origin main
          deactivate
  docs_windows:
    name: Generate windows role documentation
    needs: docs_ubuntu
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.template
          ref: main
      - name: Generate windows role documentation
        working-directory: 'trippsc2.template'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/windows
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update windows role documentation." || /bin/true
          git push origin main
          deactivate
